### ISSUE TITLE
Required field fails when I18N is enabled

### ISSUE THREAD

**Issue by aalmiray** [dlemmermann/formsfx#32]
Define a `Field` with `required(true)` and enabled I18N by invoking `i18n()`. This will cause an exception because there's no `errorMessage` associated with this field however the `errorMessageKey` property has an empty String as value but the check is made against a `null` value.

The offending code is found in `DataField.validate()`

        if (!validateRequired(newValue)) {
            if (isI18N() && requiredErrorKey.get() != null) {
                errorMessageKeys.setAll(requiredErrorKey.get());
            } else if (requiredError.get() != null) {
                errorMessages.setAll(requiredError.get());
            }

            valid.set(false);
            return false;
        }

Interestingly enough, formatting after transforming the value (inside the same `validate()` method) has the correct check

        try {
            transformedValue = valueTransformer.transform(newValue);
        } catch (Exception e) {
            if (isI18N() && !formatErrorKey.get().isEmpty()) {
                errorMessageKeys.setAll(formatErrorKey.get());
            } else if (!formatError.get().isEmpty()) {
                errorMessages.setAll(formatError.get());
            }

            valid.set(false);
            return false;
        }

Full stack trace follows

    Exception in thread "JavaFX Application Thread" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key 
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at com.dlsc.formsfx.model.util.ResourceBundleService.translate(ResourceBundleService.java:62)
        at com.dlsc.formsfx.model.structure.Field.lambda$null$5(Field.java:170)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.dlsc.formsfx.model.structure.Field.lambda$new$6(Field.java:171)
        at com.sun.javafx.binding.ListExpressionHelper$SingleChange.fireValueChangedEvent(ListExpressionHelper.java:239)
        at com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:109)
        at javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:200)
        at javafx.beans.property.ListPropertyBase.lambda$new$39(ListPropertyBase.java:56)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at javafx.collections.ObservableListBase.setAll(ObservableListBase.java:250)
        at javafx.beans.binding.ListExpression.setAll(ListExpression.java:364)
        at com.dlsc.formsfx.model.structure.DataField.validate(DataField.java:303)
        at com.dlsc.formsfx.model.structure.DataField.lambda$new$3(DataField.java:126)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
        at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
        at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
        at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
        at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
        at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
        at com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:599)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
        at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
        at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1332)
        at javafx.scene.control.TextInputControl$TextProperty.access$1600(TextInputControl.java:1300)
        at javafx.scene.control.TextInputControl.lambda$new$162(TextInputControl.java:139)
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.scene.control.TextField$TextFieldContent.delete(TextField.java:96)
        at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1200)
        at javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:556)
        at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:548)
        at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:510)
        at javafx.scene.control.TextInputControl.replaceSelection(TextInputControl.java:1084)
        at javafx.scene.control.TextInputControl.deletePreviousChar(TextInputControl.java:889)
        at com.sun.javafx.scene.control.skin.TextFieldSkin.deleteChar(TextFieldSkin.java:589)
        at com.sun.javafx.scene.control.behavior.TextFieldBehavior.deleteChar(TextFieldBehavior.java:198)
        at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.deletePreviousChar(TextInputControlBehavior.java:311)
        at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callAction(TextInputControlBehavior.java:143)
        at com.sun.javafx.scene.control.behavior.BehaviorBase.callActionForEvent(BehaviorBase.java:218)
        at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callActionForEvent(TextInputControlBehavior.java:127)
        at com.sun.javafx.scene.control.behavior.BehaviorBase.lambda$new$74(BehaviorBase.java:135)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
        at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
        at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$352(GlassViewEventHandler.java:248)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
        at com.sun.glass.ui.View.notifyKey(View.java:966)

**Comment by aalmiray** [comment]
Fixed.
